# MathGene Azure Pipeline

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

strategy:
  matrix:
    node_10_x:
      node_version: 10.x
    node_9_x:
      node_version: 8.x

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)
- script: |
    npm install --save-dev jest
    npm install --save-dev jest-junit-reporter
    npm test
  displayName: 'Run test script'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '$(System.DefaultWorkingDirectory)/**/test-report.xml'
- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
