# MathGene Azure Pipeline

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

strategy:
  matrix:
    node_10_x:
      node_version: 10.x
    node_9_x:
      node_version: 9.x
steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)
- script: |
    npm install --save-dev jest
    npm test
  displayName: 'Run test script'
